package com.example.gramasuvidha // Your package

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.viewModels
import com.example.gramasuvidha.ui.screens.MainAppScreen
import com.example.gramasuvidha.ui.theme.GramaSuvidhaTheme // Generated by Android Studio
import com.example.gramasuvidha.viewmodels.ProjectViewModel

class MainActivity : ComponentActivity() {
    // Instantiate ViewModel at the Activity level
    private val viewModel: ProjectViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            GramaSuvidhaTheme {
                MainAppScreen(viewModel = viewModel)
            }
        }
    }
}